### ISSUE TITLE
Please create a github release to match the video before making changes

### ISSUE THREAD

**Issue by dave42w** [bcampolo/nvim-starter-kit#1]
Please would you release a video compatible version before you make any changes.

Then as you update we can still start with what is consistent with the video. I've had this problem with someone else's video where the github no longer matched the video and there was no tag or release to find which point in the github matched the video instructions.

Thanks

**Comment by bcampolo** [comment]
Great idea!  I created release tag v0.0.1 to align with the video and updated some of the show notes in the video description to provide both the latest and the one that aligns with the video.
