### ISSUE TITLE
 "git branch checkout python"

### ISSUE THREAD

**Issue by Wen-Xue-Gogo** [bcampolo/nvim-starter-kit#10]
In the instruction, I think you mean to say. "git branch checkout python", not just "git checkout python"

**Comment by bcampolo** [comment]
Hi @Wen-Xue-Gogo, thank you for taking a look at the Starter Kit.  I do believe "git checkout python" is correct.  If you cloned the repo before I created the python branch you may need to run "git fetch origin python" first.
