### ISSUE TITLE
vim-isort will be disabled

### ISSUE THREAD

**Issue by afreisinger** [bcampolo/nvim-starter-kit#11]
Hi !

I have the following problem when editing a py file. I use nvchad and pyenv. 
I configured init.lua with vim.g.python3_host_prog = '/usr/bin/python3' and providers server enabledcand and isort installed
I have the following problem when editing a py file. 

.local/share/nvim/lazy/vim-isort/plugin/python_vimisort.vim[140]..function provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require[12]..pro
vider#Poll, en la línea 7
Vim(if):Error invoking 'poll' on channel 3:^@Invalid channel: 3

REgards

TAnks !

**Comment by bcampolo** [comment]
Hi @afreisinger ,  Sorry, I'm not very familiar with NVChad.  If you are using the Starter Kit here I can probably be more helpful.
