### ISSUE TITLE
LSP config (neodev.nvim)

### ISSUE THREAD

**Issue by mohammadlashkari** [bcampolo/nvim-starter-kit#14]
Hi. In the LSP config file, I think we should initialize `folke/neodev.nvim` like this:
```
{'folke/neodev.nvim', opts = {}}
```
to ensure it works.

**Comment by bcampolo** [comment]
You are right, I will make that change

**Comment by bcampolo** [comment]
Sorry, thought I pushed this a while ago, but this update is now in there.
