### ISSUE TITLE
Can Maven projects be created?

### ISSUE THREAD

**Issue by Mike-18awq** [bcampolo/nvim-starter-kit#15]
Can Maven projects be created or executed? Or does it require additional configuration? And if it is possible, how can they be created and/or executed?

**Comment by bcampolo** [comment]
Mason is a plugin for Neovim that helps to automate the installation of LSPs and other supporting tools.  You can see how I've configured it in the Neovim Starter Kit for Java here: https://github.com/bcampolo/nvim-starter-kit/blob/java/.config/nvim/lua/plugins/nvim-lspconfig.lua.  Can you explain what it is you are trying to do and any problems that you might be facing?

**Comment by Mike-18awq** [comment]
It was Maven, sorry haha

**Comment by bcampolo** [comment]
The Starter Kit for Java should automatically find your pom and load dependencies.  You can run mvn commands either in the terminal or command area.  I also found this plugin but I've not tried it: https://github.com/eatgrass/maven.nvim
Which lets you interactively run Maven commands.  I tend to use Gradle mostly so I'm a little rusty with Maven.  After you get it working let me know if there is anything that would be helpful to add to the Starter Kit.

**Comment by bcampolo** [comment]
Closing due to no response.  Hopefully you were able to get it all working.
