### ISSUE TITLE
Failed to run `config` for nvim-dap-ui

### ISSUE THREAD

**Issue by Marvinus** [bcampolo/nvim-starter-kit#17]
Failed to run `config` for nvim-dap-ui

...se/.local/share/nvim/lazy/nvim-dap-ui/lua/dapui/init.lua:36: nvim-dap-ui requires nvim-nio to be installed. Instal
l from https://github.com/nvim-neotest/nvim-nio

# stacktrace:
  - .config/nvim/lua/plugins/nvim-dap-ui.lua:91 _in_ **config**

**Comment by 6iu8a** [comment]
Just add these two lines to fix it.
![DF1C4500-4A96-49e3-9B98-D44C566F860D](https://github.com/bcampolo/nvim-starter-kit/assets/172493461/326be5d5-4b9f-4dce-8925-5b15a851e2a5)

**Comment by bcampolo** [comment]
Thanks, this must have been updated in a newer version of nvim-dap-ui.  I've made the updates.
