### ISSUE TITLE
Fidget

### ISSUE THREAD

**Issue by cipherodio** [bcampolo/nvim-starter-kit#18]
Fidget is not working, even though a client is already attached to a buffer.

**Comment by bcampolo** [comment]
Can you provide more details on what is happening vs what you are expecting?  Are there any error messages?

**Comment by cipherodio** [comment]
If i open a lua file, there is no fidget notification on bottom right corner about loading workspace or anything, even though `lua-ls` is attached to buffer. There is no error message that shows up.

**Comment by bcampolo** [comment]
Are you using lazy.nvim?  If so, can you run the :Lazy command and see if fidget is installed and in the 'Loaded' list?  If there were any install issues it would show the error there.  If it wasn't loaded it would be in the 'Not Loaded' list at the bottom.  I tried opening a Lua file with my config and it does show things like 'Loading Workspace' in the bottom right corner with fidget.  Are you using my Starter Kit as a starting point or did you just take specific parts of it?  Can you provide your nvim-lspconfig plugin configuration?

**Comment by cipherodio** [comment]
I'm using only your starter kit `python` branch only but still it doesn't show fidget, but with my old configuration the fidget is showing up. so i'm confused what is wrong.

**Comment by cipherodio** [comment]
I just noticed that when i open a `lua` file outside of `~/.config/nvim/` directory, fidget is showing up, but it's fidget is not working inside `~/.config/nvim/` directory.

**Comment by bcampolo** [comment]
Is there any way you can share your config?

**Comment by cipherodio** [comment]
im  only using your default starter kit python sir.

**Comment by bcampolo** [comment]
What version of Neovim are you using?  All of my setup was done with 0.9.5.  Also, when you first set everything up, if you want to use the exact versions of the plugins that I am using, you can do ':Lazy restore' to reset all plugins to the same versions that I have locked in the repo.  If you never ran this command it would try to install the latest versions of each and there are likely new conflicts introduced.

**Comment by cipherodio** [comment]
I'm using `neovim v0.10` on linux. i'll try to do `:Lazy restore` later as i'm on my phone. thank you

**Comment by bcampolo** [comment]
If that doesn't work, it could be an incompatibility with Neovim v0.10.0.  Just my opinion, but I never take a .0 release of anything.  I always wait for something more stable.

**Comment by cipherodio** [comment]
hi sir, your latest commit fixed the issue `{ "folke/neodev.nvim", opts = {} },` thanks for your time sir
