### ISSUE TITLE
Plugin naming

### ISSUE THREAD

**Issue by dave42w** [bcampolo/nvim-starter-kit#2]
Would it be possible to name the plugs exactly the same as their github respositories? It makes it much easier to compare to other lists and to find the documentation

eg
`autopairs.lua => nvim-autopairs.lua`

At the same time maybe a comment at the top of each with the url to provide direct access to the master github (make sure we don't accidentally go to a fork)?

eg for autopairs add
`-- https://github.com/windwp/nvim-autopairs`

I'm happy to submit a PR (but please after a release has been done so we can still go back to what matches the video).

The plugins I've noticed are:

- autopairs.lua => nvim-autopairs.lua
- git-blame.lua => git-blame-nvim.lua
- indent-blankline => indent-blankline-nvim.lua
- lsp.lua => nvim-lspconfig.lua
- lualine.lua => lualine-nvim.lua
- nvim-dap.lua => nvim-dap-ui.lua
- telescope.lua => telescope-nvim.lua
- treesitter.lua => nvim-treesitter.lua

Several of these can't be done exactly eg git-blame.nvim.lua wouldn't work as a filename. I've replaced the . with - which is definitely not ideal.
One exception to the plugin naming might be colorscheme where it might make more sense to keep the plugin name the same when switching between schemes.

**Comment by bcampolo** [comment]
I started making this change (tagged the version beforehand) and ran into the .nvim issue you mentioned.  I think using a dash is OK like you said so I can do that.  As far as adding the URL comment, I started doing this, but then noticed there are a decent number of dependencies that are also github URLs.  Would you expect each dependency to also have a URL comment?  Might get a bit messy.  Is the value of the URL comment just for convenience?  I'm asking because the first parameter of the lazy spec is the URI path that comes after the standard https://github.com/, so from an information standpoint, you don't gain much, but I can see it being a slight convenience.

**Comment by dave42w** [comment]
> I started making this change (tagged the version beforehand) and ran into the .nvim issue you mentioned. I think using a dash is OK like you said so I can do that. 

That's great. I can't think of a better option than the - instead of .

> As far as adding the URL comment, I started doing this, but then noticed there are a decent number of dependencies that are also github URLs. Would you expect each dependency to also have a URL comment? Might get a bit messy. Is the value of the URL comment just for convenience? I'm asking because the first parameter of the lazy spec is the URI path that comes after the standard https://github.com/, so from an information standpoint, you don't gain much, but I can see it being a slight convenience.

This is the sort of thing that I suspect is most helpful for the very newest users but I realise that it has a maintenance cost to keep them in line and it is obvious for more experienced users. So I'm not sure, especially as I agree if it is done it needs to be consistent to dependencies.
Maybe a standard comment such as 
```
  -- LSP Configuration
  -- Plugin source at "https://github.com/" plus name below
  'neovim/nvim-lspconfig',
```
This wouldn't require any ongoing maintenance, but wouldn't provide a clickable link to the plugin readme on github.

So I don't have a very strong view, happy to leave it to your preference.

**Comment by bcampolo** [comment]
This should be resolved with https://github.com/bcampolo/nvim-starter-kit/commit/4758a99908d7825fb6392f3d8e87e78b543b88df
