### ISSUE TITLE
dap-ui Failed to run config for nvim-dap

### ISSUE THREAD

**Issue by pannet1** [bcampolo/nvim-starter-kit#20]
i have not made any change to the 

![image](https://github.com/user-attachments/assets/cb168a63-8d19-4bf8-9d8b-093e69c24307)

i am using many virtual environment for all my projects. may be absolute path to python interpreter within each venv would help.

**Comment by bcampolo** [comment]
What version of Neovim are you using?

**Comment by pannet1** [comment]
> What version of Neovim are you using?

```
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1720049189
```

**Comment by bcampolo** [comment]
Are you using the Starter Kit as is or did you make modifications yet?  The Starter Kit uses version 0.9.x.  I tend to not upgrade things too soon when new versions come out to prevent incompatibilities but I don't know for sure if that's what is causing your error.  If lazy is running correctly you could try :Lazy restore.  This will restore all plugin versions to the versions I had in the lazy-lock file.  If that still doesn't work can you send me your dap configuration (assuming it is not identical to mine)?

**Comment by pannet1** [comment]
> Are you using the Starter Kit as is or did you make modifications yet? The Starter Kit uses version 0.9.x. I tend to not upgrade things too soon when new versions come out to prevent incompatibilities but I don't know for sure if that's what is causing your error. If lazy is running correctly you could try :Lazy restore. This will restore all plugin versions to the versions I had in the lazy-lock file. If that still doesn't work can you send me your dap configuration (assuming it is not identical to mine)?

got it .. i was using Lazy starter kit. i have added my own lua configs and trying to merge yours (by maually adding those lua files one after the other). i guess, i need little more knowledge to do this. thank you for your support. you may close this.
