### ISSUE TITLE
indentation looks a bit off in java

### ISSUE THREAD

**Issue by milind-shakya-sp** [bcampolo/nvim-starter-kit#22]
```java
 | | |   private final String m_result;
 | |
```

For eg in the above snippet, if I hit enter after semicolon, I end up 4 spaces before private in the next new line.

Sorry to the short description. Will try to add more info if you need.

**Comment by bcampolo** [comment]
The indentation uses treesitter, so it doesn't necessarily indent based on the indentation of the line you are hitting enter on, but instead it will indent based on how deep you are in the condition/loop blocks and on the formatter which defaults to two spaces per level of indentation.  If you provide a sample file as an example I can provide more help.
