### ISSUE TITLE
Dap is not configured 

### ISSUE THREAD

**Issue by ghost** [bcampolo/nvim-starter-kit#28]
![Screenshot From 2024-12-08 22-23-42](https://github.com/user-attachments/assets/bd717809-3e53-455d-afbf-d8ff8c0e9fb6)

**Comment by ghost** [comment]
Hi i don't even see a dap configuratin file for python

**Comment by ghost** [comment]
i am sorry but previous nvim for python was configured differently so i got a little bit confused my  previous configuration for python was configured differently so i got am sorry but pr a little bit lost in your structure just point me to the file i have to fix. etc i am currently using ubuntu .

**Comment by bcampolo** [comment]
Based on your screen shot it doesn't look like you are using the python branch of my starter kit.  Python has it's own dap plugin called nvim-dap-python.lua.  Did you follow the steps in the video https://youtu.be/jWZ_JeLgDxU?si=45t8bIqO9fpX76gR
?

**Comment by ghost** [comment]
thanks a lot my mistake

**Comment by bcampolo** [comment]
Were you able to get it working?

**Comment by ghost** [comment]
well still got a lot of errors , probably because of trying on macos

**Comment by bcampolo** [comment]
Were you starting from the python starter kit or from your own config?
