### ISSUE TITLE
/usrr/bi/python exited with code 1

### ISSUE THREAD

**Issue by ghost** [bcampolo/nvim-starter-kit#29]
![Screenshot From 2024-12-12 07-58-02](https://github.com/user-attachments/assets/360b0c6c-796c-4694-b919-31ff7c977041)

**Comment by ghost** [comment]
Hi sorry to bother you so much but i have no luck with nvim-starter-kit and this is on ubuntu
nothing goes right pip is not working inside the nvim like pip install neovim, pip install isort etc
give me an error,  something else if would be nice to make user lua would be much ease to add plugins without breaking the system. else would you mind to make nvim-starter-kit for mac?

**Comment by bcampolo** [comment]
Hi, what version of Neovim are you using?  Also, did you follow all of the instructions in the original starter kit video?  Did you run :checkhealth and fix any errors you found?  Did you update the python location to python3?  If pip install is not working then there are bigger problems beyond Neovim.  Do you have python3 and pip added to your PATH?

Neovim is not an IDE out of the box.  To get it to be an IDE takes a decent amount of configuration and troubleshooting but for me that is the fun part.

I noticed you have a bunch of other open issues.  Have any of those been resolved?  If so please close them.

**Comment by ghost** [comment]
i appreciate your help . it was a pleasure.
