### ISSUE TITLE
nvim-lspconfig.lua line 27 etc: turn "# requires npm to be installed" into a comment

### ISSUE THREAD

**Issue by dave42w** [bcampolo/nvim-starter-kit#5]
In nvim-lspconfig.lua there are various commented out plugins that have "# requires npm to be installed"

eg

```
        -- "bashls", # requires npm to be installed
```

My suggestion is to change the # so that if we uncomment the line the `# bash` is already a comment
ie
```
        -- "bashls", -- # requires npm to be installed
```
this saves us changing `# requires npm to be installed` into a comment (or deleting it)

I do appreciate the idea that currently the invalid lua line might encourage first timers to really take note of the need to install npm, but on balance I think the hassle reduction for everyone else is worth it :-)

**Comment by bcampolo** [comment]
Good catch.  This is done
