### ISSUE TITLE
Add Neogit

### ISSUE THREAD

**Issue by dave42w** [bcampolo/nvim-starter-kit#6]
I've looked around and decided (for the moment at least) that I like Neogit as a UI for handling git tasks.

As a plugin neogit.lua
```
return {
  -- https://github.com/NeogitOrg/neogit
  "NeogitOrg/neogit",
  dependencies = {
    "nvim-lua/plenary.nvim",         -- required
    "sindrets/diffview.nvim",        -- optional - Diff integration

    -- Only one of these is needed, not both.
    "nvim-telescope/telescope.nvim", -- optional
    --"ibhagwan/fzf-lua",              -- optional
  },
  config = true
}
```

As a keymap I have added 
```
-- neogit.lua
keymap.set("n", '<leader>ng', ":Neogit<cr>")
```

Are you interested?

**Comment by bcampolo** [comment]
I'll add it to the list of plugins to be reviewed.  I've seen a lot of others use fugitive as well and I haven't come to any conclusions myself yet.
