### ISSUE TITLE
Replace Black and isort with Ruff formatter

### ISSUE THREAD

**Issue by davidbrochart** [bcampolo/nvim-starter-kit#8]
For the [Neovim Starter Kit for Python](https://github.com/bcampolo/nvim-starter-kit/tree/python?tab=readme-ov-file#neovim-starter-kit-for-python-), it might be better to use [Ruff formatter](https://docs.astral.sh/ruff/formatter/) instead of Black and isort?

**Comment by bcampolo** [comment]
Can you explain why it might be better?

**Comment by davidbrochart** [comment]
The Ruff formatter is much faster, and does what all these separate tools do.
