### ISSUE TITLE
Thanks for the effort. Tried MacOS... Mason failed to install groovyls, just so you know.

### ISSUE THREAD

**Issue by elu1elu1** [bcampolo/nvim-starter-kit#9]

**Comment by elu1elu1** [comment]
dependencies missing?

**Comment by bcampolo** [comment]
I've been thinking about removing groovyls from the starter kit.  Gradle/groovy is part of my workflow but probably isn't for most people.  Do you use Gradle/groovy?

**Comment by elu1elu1** [comment]
I only know python and interested in machine learning.

**Comment by bcampolo** [comment]
I removed a few of the LSPs from the base Starter Kit and the Python Starter Kit which were geared more towards other specialized workflows (e.g. Java/PHP).  This should indirectly resolve the issue you were having.  Closing this issue, but let me know if this doesn't work for you.

**Comment by Mike-18awq** [comment]
rm -rf ~/.local/share/nvim/lazy/nvim-treesitter/queries/groovy
